### ISSUE TITLE
Option to avoid export waypoints in the track

### ISSUE THREAD

**Issue by DGrv** [tmuguet/map2gpx#13]
Personnaly the waypoints in the track are more disturbing me when I use the gpx in other app or software. 

- First what is your opinion, does someone is using the points or find this usefull.
- Second, would it be possible to give the user an option to export only the track ?

Thanks

**Comment by tmuguet** [comment]
These points could be useful is you wish to re-import the file and edit its path (feature not yet available)... Other than that, these points are pointless IMO. I'll just remove the waypoints, and add an option to export or not the stopovers.
