### ISSUE TITLE
Export multitrack as single track

### ISSUE THREAD

**Issue by javierpose** [tmuguet/map2gpx#18]
When you export a track, you have the option "Include the stepover markers". I would like to add an option to create as a simple track because many devices (Garmin, Suunto ...) do not support multitracks and only show the first track (first `<trk>` ... `</trk>`) of a multitrack. I tried to modify it but I haven't found a way to do it, could you help me? Thank you very much

**Comment by tmuguet** [comment]
Hi,

Thank you for your feedback. I'll take a look in the next few days to add that option in [Leaflet.TrackDrawer](https://github.com/tmuguet/Leaflet.TrackDrawer/issues/3) and propagate it in this project.
