### ISSUE TITLE
is mapquest dead?

### ISSUE THREAD

**Issue by javierpose** [tmuguet/map2gpx#45]
It seems that mapquest is not working anymore, any alternative?

**Comment by tmuguet** [comment]
Hi @javierpose ,

Thanks for your input. It seems mapquest is not working anymore; I don't know if it's temporary or not.

[Open Topo Data](https://www.opentopodata.org/#public-api) and [Open Elevation](https://github.com/Jorl17/open-elevation) could be alternatives (I created a ticket on the [corresponding repo](https://github.com/tmuguet/Leaflet.TrackStats/issues/30)). I'll look into it when I have some time, hopefully next week.

**Comment by tmuguet** [comment]
Hi,

I replaced mapquest by [Open Elevation](https://github.com/Jorl17/open-elevation) which seems to work quite nicely.

[Open Topo Data](https://www.opentopodata.org/) could also be used if you run your own instance of it and host your own version of map2gpx.
