### ISSUE TITLE
Problem calcul des distances :  0% - An error occured 

### ISSUE THREAD

**Issue by dlamalice** [tmuguet/map2gpx#61]
Hello,

Il y a actuellement un problème pour le calcul des distances, que ça soit sur https://map2gpx.fr ou .eu.
(message " 0% - Une erreur est survenue " dans la fenêtre du bas).
Pourriez vous corriger ? 
Merci pour map2gpx qui est très pratique pour préparer ses randos.
![image](https://user-images.githubusercontent.com/26234046/233829096-b6f5db06-efa7-4366-a47c-3f3437a16db8.png)

**Comment by tmuguet** [comment]
Bonjour @dlamalice ,

Merci pour cette remontée de bug, je regarderai cela ce week-end.

**Comment by tmuguet** [comment]
@dlamalice map2gpx.fr est en principe réparé, je vais regarder pour map2gpx.eu qui a d'autres soucis en plus...

**Comment by dlamalice** [comment]
Bonjour,
Super, je confirme que ça refonctionne.
Merci pour la rapidité de correction !
